title : SeungJun Blog
description: 'Moves like Ultra'

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: https://piacu.github.io/
plugins: [jekyll-gist]
permalink: /:year/:month/:title.html